In [ ]:
# filter/clean up data frame and write into filtered.csv
import pandas as pd
df = pd.read_csv('innocence_project_stats.csv')
col_names = list(df)
col_names

In [ ]:
# reorder and drop columns
df = df[['LastName', 'FirstName', 'Age', 'Race', 'Crime', 'Sentence', 'Convicted', 'Exonerated', 'DNA', "ST", "County"]]
print(list(df))

In [ ]:
# make 1 column for Name and remove the 2 name columns

df['Name'] = df.insert(0, 'Name', None)
df["Name"] = df["FirstName"] + " " + df["LastName"]
df = df.drop(columns=["FirstName", "LastName"])
df

In [ ]:
# make Age an int value (why float?)
df["Age"] = df["Age"].astype("Int8")

In [ ]:
# Flag those with sentences containing Life

# new column for Life sentences (True/False)
df['Life'] = df.insert(5, 'Life', None)
print(list(df))

In [ ]:

for i,row in df.iterrows(): 
    #print (i, list(row))  # DEBUG: row has values for the row with the index i
    s = row["Sentence"] # sentence
    if 'life' in s.lower():
        df.loc[i, "Life"] = True   
    else:
        df.loc[i, "Life"] = False

df

In [ ]:
# drop those with Life == "False"
df = df.drop(df[df["Life"] == False].index)
df

In [ ]:
# Now also drop Life column as it's no longer needed
df = df.drop("Life", axis=1)

In [ ]:
# add a new column with duration (Exonerated - Convicted)
df['Duration'] = df.insert(5, 'Duration', 0)
df["Duration"] = df["Exonerated"] - df["Convicted"]
df

In [ ]:
# For DNA use True and False, not DNA and NaN 
for i,row in df.iterrows(): 
    #print (i, list(row))  # DEBUG: row has values for the row with the index i
    if row["DNA"] == "DNA":
        df.loc[i, "DNA"] = True   # short for  blue
    else:
        df.loc[i, "DNA"] = False
df

In [ ]:
#add median age
age_med = df['Age'].median()

print(age_med)

In [ ]:
#State with most exonerations
from collections import Counter
data = Counter(df['ST'])
AllStates = data.most_common()   # Returns all unique items and their counts
Most_State = data.most_common(1)  # Returns the highest occurring item
print(Most_State)

In [ ]:
#Use same method to find largest racial group
data = Counter(df['Race'])
Race_Counts = data.most_common()
Most_Race = data.most_common(1)  # Returns all unique items and their counts
print("The largest Racial group is:", Most_Race)  # Returns the highest occurring item

In [ ]:
#Find the most common crime

data = Counter(df['Crime'])
Most_Crimes = data.most_common()   # Returns all unique items and their counts
Most_Crimes1 = data.most_common(1)  # Returns the highest occurring item
print(Most_Crimes1)

In [ ]:
#Create List of names for each state

#I need to match states with names 

ST_List= []

In [ ]:
# re-build a 0 to N continuous index
df = df.reset_index(drop=True)
df.index.name = "#"
df

In [ ]:
# Save to new file
df.to_csv("filtered.csv")

In [5]:
# Summarize by State:
import pandas as pd
df = pd.read_csv("filtered.csv")

# Convert F- States
for i,row in df.iterrows(): 
    if row["ST"][0:2] == "F-":
            st = row["ST"][2:]  # CH was [3:] !!!!
            df.loc[i, "ST"] =  st 

df["ST"].unique()

array(['NC', 'NY', 'IL', 'PA', 'LA', 'CT', 'CA', 'OH', 'MS', 'TX', 'WA',
       'WI', 'MO', 'VA', 'MI', 'RI', 'OK', 'MD', 'TN', 'FL', 'NJ', 'MA',
       'WV', 'SC', 'NV', 'KS', 'OR', 'AR', 'UT', 'GA', 'MT', 'DC', 'IN',
       'PR', 'KY', 'AL', 'DE', 'CO', 'WY', 'NM', 'IA', 'AZ', 'VT', 'NE',
       'HI', 'ID'], dtype=object)

In [6]:
avgAgebyST = df.groupby("ST")["Age"].mean().round(2)
avgDurbyST = df.groupby("ST")["Duration"].mean().round(2)
DNAprbbyST = df.groupby("ST")["DNA"].mean().round(2)
dfST = pd.concat([avgAgebyST, avgDurbyST, DNAprbbyST], axis=1)
dfST = dfST.rename(columns={'Age':'AvgAge', 'Duration':'AvgDurationYrs', "DNA":"DNAprob"})
dfST

    AvgAge  AvgDurationYrs  DNAprob
ST
AL   28.78           10.11     0.22
AR   28.00           15.40     0.20
AZ   36.00            9.00     0.00
CA   26.42           14.31     0.15
CO   24.50            8.50     0.50
CT   24.50           17.25     0.25
DC   21.33           29.31     0.31
DE   18.00           38.00     0.00
FL   25.14           16.86     0.26
GA   27.78           15.47     0.31
HI   20.00           23.00     1.00
IA   27.00           16.00     0.00
ID   24.50           18.50     0.50
IL   23.95           20.55     0.28
IN   34.50            7.50     0.50
KS   28.67           14.83     0.50
KY   24.80           22.60     0.40
LA   23.32           20.91     0.30
MA   23.78           23.70     0.20
MD   21.80           19.52     0.16
MI   24.00           18.45     0.09
MO   27.89           13.46     0.21
MS   28.00           15.90     0.50
MT   26.50           16.50     0.00
NC   28.44           19.15     0.44
NE   23.00           27.00     0.50
NJ   30.14           18.00     0.36
NM   32.50           13.25     0.00
NV   30.10           18.60     0.10
NY   24.12           17.96     0.12
OH   29.21           15.49     0.23
OK   23.00           11.71     0.29
OR   30.33            6.44     0.33
PA   25.12           17.18     0.09
PR   21.75           16.75     0.75
RI   23.50            5.00     0.00
SC   29.20           12.00     0.40
TN   28.77           16.46     0.15
TX   28.28           16.34     0.58
UT   32.29            7.36     0.21
VA   26.12           20.24     0.35
VT   32.00           18.00     1.00
WA   38.33           12.83     0.17
WI   28.00           13.56     0.50
WV   26.00           12.00     0.29
WY   31.67            9.33     0.33

In [7]:
numinmatesST = df.value_counts("ST")
numinmatesST = numinmatesST.rename("NumInmates")
dfST = pd.concat([dfST, numinmatesST], axis=1)
dfST

    AvgAge  AvgDurationYrs  DNAprob  NumInmates
ST
AL   28.78           10.11     0.22           9
AR   28.00           15.40     0.20           5
AZ   36.00            9.00     0.00           1
CA   26.42           14.31     0.15         124
CO   24.50            8.50     0.50           6
CT   24.50           17.25     0.25           4
DC   21.33           29.31     0.31          13
DE   18.00           38.00     0.00           1
FL   25.14           16.86     0.26          35
GA   27.78           15.47     0.31          32
HI   20.00           23.00     1.00           1
IA   27.00           16.00     0.00           4
ID   24.50           18.50     0.50           2
IL   23.95           20.55     0.28          64
IN   34.50            7.50     0.50           2
KS   28.67           14.83     0.50           6
KY   24.80           22.60     0.40           5
LA   23.32           20.91     0.30          54
MA   23.78           23.70     0.20          40
MD   21.80           19.52     0.16          25
MI   24.00           18.45     0.09          56
MO   27.89           13.46     0.21          28
MS   28.00           15.90     0.50          10
MT   26.50           16.50     0.00           2
NC   28.44           19.15     0.44          27
NE   23.00           27.00     0.50           2
NJ   30.14           18.00     0.36          14
NM   32.50           13.25     0.00           4
NV   30.10           18.60     0.10          10
NY   24.12           17.96     0.12         160
OH   29.21           15.49     0.23          39
OK   23.00           11.71     0.29          17
OR   30.33            6.44     0.33           9
PA   25.12           17.18     0.09          65
PR   21.75           16.75     0.75           4
RI   23.50            5.00     0.00           2
SC   29.20           12.00     0.40           5
TN   28.77           16.46     0.15          13
TX   28.28           16.34     0.58          64
UT   32.29            7.36     0.21          14
VA   26.12           20.24     0.35          17
VT   32.00           18.00     1.00           1
WA   38.33           12.83     0.17           6
WI   28.00           13.56     0.50          16
WV   26.00           12.00     0.29           7
WY   31.67            9.33     0.33           3

In [8]:
race =df.groupby("ST")["Race"].apply(pd.Series.mode)

state_list = []
maj_race_list = []
for st in race.index:
    #print(st, race.loc[st])
    if st[1] == 0:
        state_list.append(st[0])
        maj_race_list.append(race.loc[st])

maj_race_by_state = pd.Series(data=maj_race_list, index=state_list)
maj_race_by_state = maj_race_by_state.rename("MajRace")
dfST = pd.concat([dfST, maj_race_by_state], axis=1)
dfST

    AvgAge  AvgDurationYrs  DNAprob  NumInmates          MajRace
AL   28.78           10.11     0.22           9            White
AR   28.00           15.40     0.20           5            Black
AZ   36.00            9.00     0.00           1            White
CA   26.42           14.31     0.15         124            Black
CO   24.50            8.50     0.50           6            White
CT   24.50           17.25     0.25           4            Black
DC   21.33           29.31     0.31          13            Black
DE   18.00           38.00     0.00           1            Black
FL   25.14           16.86     0.26          35            Black
GA   27.78           15.47     0.31          32            White
HI   20.00           23.00     1.00           1            Other
IA   27.00           16.00     0.00           4            Black
ID   24.50           18.50     0.50           2  Native American
IL   23.95           20.55     0.28          64            Black
IN   34.50            7.50     0.50           2            White
KS   28.67           14.83     0.50           6            White
KY   24.80           22.60     0.40           5            White
LA   23.32           20.91     0.30          54            Black
MA   23.78           23.70     0.20          40            Black
MD   21.80           19.52     0.16          25            Black
MI   24.00           18.45     0.09          56            Black
MO   27.89           13.46     0.21          28            Black
MS   28.00           15.90     0.50          10            Black
MT   26.50           16.50     0.00           2            White
NC   28.44           19.15     0.44          27            Black
NE   23.00           27.00     0.50           2            White
NJ   30.14           18.00     0.36          14            Black
NM   32.50           13.25     0.00           4            White
NV   30.10           18.60     0.10          10            White
NY   24.12           17.96     0.12         160            Black
OH   29.21           15.49     0.23          39            Black
OK   23.00           11.71     0.29          17            Black
OR   30.33            6.44     0.33           9            White
PA   25.12           17.18     0.09          65            Black
PR   21.75           16.75     0.75           4         Hispanic
RI   23.50            5.00     0.00           2         Hispanic
SC   29.20           12.00     0.40           5            White
TN   28.77           16.46     0.15          13            White
TX   28.28           16.34     0.58          64            Black
UT   32.29            7.36     0.21          14            White
VA   26.12           20.24     0.35          17            White
VT   32.00           18.00     1.00           1            White
WA   38.33           12.83     0.17           6            White
WI   28.00           13.56     0.50          16            Black
WV   26.00           12.00     0.29           7            White
WY   31.67            9.33     0.33           3            White

In [ ]:
dfST.index.name = "ST"
dfST.to_csv("StateAggregates.csv")

In [ ]:
# append lat/long of country


# read in US counties DB
df_counties = pd.read_csv("uscounties.csv")
display(df_counties.head(5))

# state controid coordinates, used if the county lookup doesn't work
df_states = pd.read_csv("state.csv")
df_states.head(5)

In [ ]:
# add 2 columns for lat and long (init wth None)
df["Lat"] = None
df["Long"] = None
df

In [ ]:
# for each row, make a query for its ST and County into the counties df

for i,row in df.iterrows(): 
        
        # query with ST and County colum 
        query_string = f'state_id == "{row["ST"]}" and county == "{row["County"]}"'  # the " around the values are needed!
        cnty = df_counties.query(query_string)

        if cnty.empty == False:  # we got a hit!
            cnty = cnty.head(1)  # use first of potentially several hits!
            lat, long = float(cnty["lat"]), float(cnty["lng"])
        else: # got no result,  try with county_full?
            query_string = f'state_id == "{row["ST"]}" and county_full == "{row["County"]}"'
            cnty = df_counties.query(query_string)

        if cnty.empty == False:
            cnty = cnty.head(1)  
            lat, long = float(cnty["lat"]), float(cnty["lng"]) 
        else:# Let's see if its  F- country
            if row["ST"][0:2] == "F-":
                st = row["ST"][2:]  # CH was [3:] !!!!
                df.loc[i, "ST"] =  st  # remove F- in data,
                row["ST"] = st  # CH the line above does not overwrite row["ST"] for some reason ...

            # find state and gt it's lat/lon
            state = df_states[df_states["postal_code"] == row["ST"]]
            
            if state.empty == False:  
                lat, long = float(state["lat"]), float(state["lng"]) 
            else:
                print("error for", row["ST"],  row["County"])
                continue
              
        df.loc[i, "Lat"] = lat 
        df.loc[i, "Long"] = long         

df

In [ ]:
# Save to new file
df.to_csv("filtered_with_latlong.csv")

In [ ]:
# Run the graphing app inside jupyter

# Import packages
from dash import Dash, html, dash_table, dcc, callback, Output, Input
import pandas as pd
import plotly.express as px

# Incorporate data
df = pd.read_csv('filtered.csv')
num_rows = len(df)

# Initialize the app
app = Dash(__name__)

# App layout
app.layout = html.Div([
    html.Div(children=f'Total of {num_rows} entries, select a Histogram ',  style={'color': 'Gold', 'font-size': 20}),
    html.Hr(),

    
    dcc.RadioItems(options=['Race', 'Crime', 'ST', 'Age', 'Duration', 'DNA' ], value='Race', 
                   inline=True, 
                   id='controls-and-radio-item',
                   style={'color': 'Gold', 'font-size': 20}),
    dcc.Graph(figure={}, id='controls-and-graph')
])

# Add controls to build the interaction
@callback(
    Output(component_id='controls-and-graph', component_property='figure'),
    Input(component_id='controls-and-radio-item', component_property='value')
)


def update_graph(col_chosen):
    fig = px.histogram(df, x=col_chosen)
    return fig

def updateTable(n):
     pass

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)